defaults = [
    {"url": "https://i.imgur.com/e4jKRa4.png", "answers": ["otter"]},
    {"url": "https://i.imgur.com/P6sPJzl.jpeg", "answers": ["dog"]},
    {"url": "https://i.imgur.com/o2kotzD.jpg", "answers": ["cat"]},
    {"url": "https://i.imgur.com/mx66SBD.jpeg", "answers": ["orange"]},
    {"url": "https://i.imgur.com/V8SS4Yk.jpeg", "answers": ["banana", "bananas"]},
    {"url": "https://media.newyorker.com/photos/5f2c85539a557880d973a759/2:2/w_1592,h_1592,c_limit/Buford-FrenchRice.jpg", "answers": ["rice"]},
    {"url": "https://cdn.shopify.com/s/files/1/0336/7167/5948/products/image-of-pumpkins-vegetables-27960732713004_600x600.jpg?v=1618238328", "answers": ["pumpkin"]},
    {"url": "https://www.collinsdictionary.com/images/full/apple_158989157.jpg", "answers": ["apple"]},
    {"url": "https://pngimg.com/uploads/sword/sword_PNG5525.png", "answers": ["sword"]},
    {"url": "https://www.spacex.com/static/images/content/fh_performance.jpg", "answers": ["rocket", "falcon heavy"]},
    {"url": "https://tesla-cdn.thron.com/delivery/public/image/tesla/3863f3e5-546a-4b22-bcbc-1f8ee0479744/bvlatuR/std/1200x628/MX-Social", "answers": ["tesla", "car"]},
    {"url": "https://media-cldnry.s-nbcnews.com/image/upload/newscms/2019_21/2870431/190524-classic-american-cheeseburger-ew-207p.jpg", "answers": ["burger"]},
    {"url": "https://images.immediate.co.uk/production/volatile/sites/30/2021/03/French-fries-b9e3e0c.jpg", "answers": ["fries", "french fries"]},
    {"url": "https://qvc.scene7.com/is/image/QVC/h/18/h227018.001", "answers": ["rug", "mat"]},
    {"url": "https://productimages.mybobs.com/20035205017/20035205017_gallery_01_wide.jpg", "answers": ["desk"]},
    {"url": "https://images.techopedia.com/images/uploads/television.jpg", "answers": ["tv", "television"]},
    {"url": "https://www.emergenthealth.org/wp-content/uploads/2020/03/082019_EHP_MRM1499.jpg", "answers": ["ambulance"]},
    {"url": "https://electrek.co/wp-content/uploads/sites/3/2022/11/Lion-electric-US-factory-1.jpeg", "answers": ["schoolbus", "school bus"]},
    {"url": "https://m.media-amazon.com/images/I/71ARSWzCZBL.jpg", "answers": ["spatula"]},
    {"url": "https://wherethewindsblow.com/wp-content/uploads/2015/07/JUMBO-Six-sided-white-dice.jpg", "answers": ["dice"]},
    {"url": "https://assets.bonappetit.com/photos/58dbf6c8a6614f6f50816994/4:3/w_2591,h_1943,c_limit/20170323%20MOB6231_FINAL_crop.jpg", "answers": ["strawberry"]},
    {"url": "https://upload.wikimedia.org/wikipedia/commons/0/0c/Cow_female_black_white.jpg", "answers": ["cow"]},
    {"url": "https://cb2.scene7.com/is/image/CB2/KMPolarTableLampSHS21/$web_pdp_main_carousel_xs$/210210135642/polar-table-lamp.jpg", "answers": ["lamp"]},
    {"url": "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6351/6351487_sd.jpg", "answers": ["flashlight"]},
    {"url": "https://cdn.mos.cms.futurecdn.net/iC7HBvohbJqExqvbKcV3pP.jpg", "answers": ["potato", "potatoes"]},
    {"url": "https://upload.wikimedia.org/wikipedia/commons/9/90/Candy-Cane-Classic_thumbnail.png", "answers": ["candycane", "candy cane"]},
    {"url": "https://www.familyhandyman.com/wp-content/uploads/2019/03/shutterstock_208428820-Chimney.jpg", "answers": ["chimney"]},
    {"url": "https://koa.com/blog/images/build-a-campfire.jpg", "answers": ["camp fire", "campfire"]},
    {"url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Chenille_de_Grand_porte_queue_%28macaon%29.jpg/800px-Chenille_de_Grand_porte_queue_%28macaon%29.jpg", "answers": ["caterpillar"]},
    {"url": "https://assets.bonappetit.com/photos/5c62e4a3e81bbf522a9579ce/5:4/w_2815,h_2252,c_limit/milk-bread.jpg", "answers": ["bread"]},
    {"url": "https://images.eatthismuch.com/img/814308_tiffanyh1_0ec52be5-fafc-4438-8706-530025a90b1d.jpg", "answers": ["toast"]},
    {"url": "https://cdn.britannica.com/64/143464-050-B0EC6714/Eggplant.jpg", "answers": ["eggplant", "eggplants"]},
    {"url": "https://cdn.britannica.com/65/12565-050-B102B3A8/crown-Denmark-helmet-form-enamel-gold-stones-1670.jpg", "answers": ["crown"]},
    {"url": "https://i.insider.com/61f83cd8415c3f0018d3c5a0?width=721&format=jpeg", "answers": ["jet", "f15", "f-15", "f-15ex"]},
    {"url": "https://upload.wikimedia.org/wikipedia/en/a/a9/MarioNSMBUDeluxe.png", "answers": ["mario"]},
    {"url": "https://upload.wikimedia.org/wikipedia/commons/e/eb/Ash_Tree_-_geograph.org.uk_-_590710.jpg", "answers": ["tree"]},
    {"url": "https://m.media-amazon.com/images/I/61Z9avu0YeL.jpg", "answers": ["lock", "masterlock", "master lock"]},
    {"url": "https://www.tastingtable.com/img/gallery/coffee-brands-ranked-from-worst-to-best/l-intro-1645231221.jpg", "answers": ["cofee"]},
    {"url": "https://ychef.files.bbci.co.uk/976x549/p0c2qddy.jpg", "answers": ["mouse"]},
    {"url": "https://www.toureiffel.paris/sites/default/files/actualite/image_principale/vue_depuisjardins_webbanner_3.jpg", "answers": ["eiffel tower"]},
]
