import re

deepl_langs = [
    {"language": "BG", "name": "Bulgarian", "supports_formality": False},
    {"language": "CS", "name": "Czech", "supports_formality": False},
    {"language": "DA", "name": "Danish", "supports_formality": False},
    {"language": "DE", "name": "German", "supports_formality": True},
    {"language": "EL", "name": "Greek", "supports_formality": False},
    # {"language": "EN-GB", "name": "English (British)", "supports_formality": False},
    # {"language": "EN-US", "name": "English (American)", "supports_formality": False},
    {"language": "EN-US", "name": "English", "supports_formality": False},
    {"language": "ES", "name": "Spanish", "supports_formality": True},
    {"language": "ET", "name": "Estonian", "supports_formality": False},
    {"language": "FI", "name": "Finnish", "supports_formality": False},
    {"language": "FR", "name": "French", "supports_formality": True},
    {"language": "HU", "name": "Hungarian", "supports_formality": False},
    {"language": "ID", "name": "Indonesian", "supports_formality": False},
    {"language": "IT", "name": "Italian", "supports_formality": True},
    {"language": "JA", "name": "Japanese", "supports_formality": True},
    {"language": "KO", "name": "Korean", "supports_formality": False},
    {"language": "LT", "name": "Lithuanian", "supports_formality": False},
    {"language": "LV", "name": "Latvian", "supports_formality": False},
    {"language": "NB", "name": "Norwegian", "supports_formality": False},
    {"language": "NL", "name": "Dutch", "supports_formality": True},
    {"language": "PL", "name": "Polish", "supports_formality": True},
    {"language": "PT-BR", "name": "Portuguese", "supports_formality": True},
    # {"language": "PT-BR", "name": "Portuguese (Brazilian)", "supports_formality": True},
    # {"language": "PT-PT", "name": "Portuguese (European)", "supports_formality": True},
    {"language": "RO", "name": "Romanian", "supports_formality": False},
    {"language": "RU", "name": "Russian", "supports_formality": True},
    {"language": "SK", "name": "Slovak", "supports_formality": False},
    {"language": "SL", "name": "Slovenian", "supports_formality": False},
    {"language": "SV", "name": "Swedish", "supports_formality": False},
    {"language": "TR", "name": "Turkish", "supports_formality": False},
    {"language": "UK", "name": "Ukrainian", "supports_formality": False},
    {"language": "ZH", "name": "Chinese", "supports_formality": False},
    # {"language": "ZH", "name": "Chinese (simplified)", "supports_formality": False},
]
google_langs = [
    {"language": "af", "name": "afrikaans", "supports_formality": False},
    {"language": "sq", "name": "albanian", "supports_formality": False},
    {"language": "am", "name": "amharic", "supports_formality": False},
    {"language": "ar", "name": "arabic", "supports_formality": False},
    {"language": "hy", "name": "armenian", "supports_formality": False},
    {"language": "az", "name": "azerbaijani", "supports_formality": False},
    {"language": "eu", "name": "basque", "supports_formality": False},
    {"language": "be", "name": "belarusian", "supports_formality": False},
    {"language": "bn", "name": "bengali", "supports_formality": False},
    {"language": "bs", "name": "bosnian", "supports_formality": False},
    {"language": "bg", "name": "bulgarian", "supports_formality": False},
    {"language": "ca", "name": "catalan", "supports_formality": False},
    {"language": "ceb", "name": "cebuano", "supports_formality": False},
    {"language": "ny", "name": "chichewa", "supports_formality": False},
    {"language": "zh-cn", "name": "chinese", "supports_formality": False},
    # {"language": "zh-cn", "name": "chinese (simplified)", "supports_formality": False},
    # {"language": "zh-tw", "name": "chinese (traditional)", "supports_formality": False},
    {"language": "co", "name": "corsican", "supports_formality": False},
    {"language": "hr", "name": "croatian", "supports_formality": False},
    {"language": "cs", "name": "czech", "supports_formality": False},
    {"language": "da", "name": "danish", "supports_formality": False},
    {"language": "nl", "name": "dutch", "supports_formality": False},
    {"language": "en", "name": "english", "supports_formality": False},
    {"language": "eo", "name": "esperanto", "supports_formality": False},
    {"language": "et", "name": "estonian", "supports_formality": False},
    {"language": "tl", "name": "filipino", "supports_formality": False},
    {"language": "fi", "name": "finnish", "supports_formality": False},
    {"language": "fr", "name": "french", "supports_formality": False},
    {"language": "fy", "name": "frisian", "supports_formality": False},
    {"language": "gl", "name": "galician", "supports_formality": False},
    {"language": "ka", "name": "georgian", "supports_formality": False},
    {"language": "de", "name": "german", "supports_formality": False},
    {"language": "el", "name": "greek", "supports_formality": False},
    {"language": "gu", "name": "gujarati", "supports_formality": False},
    {"language": "ht", "name": "haitian creole", "supports_formality": False},
    {"language": "ha", "name": "hausa", "supports_formality": False},
    {"language": "haw", "name": "hawaiian", "supports_formality": False},
    {"language": "iw", "name": "hebrew", "supports_formality": False},
    {"language": "he", "name": "hebrew", "supports_formality": False},
    {"language": "hi", "name": "hindi", "supports_formality": False},
    {"language": "hmn", "name": "hmong", "supports_formality": False},
    {"language": "hu", "name": "hungarian", "supports_formality": False},
    {"language": "is", "name": "icelandic", "supports_formality": False},
    {"language": "ig", "name": "igbo", "supports_formality": False},
    {"language": "id", "name": "indonesian", "supports_formality": False},
    {"language": "ga", "name": "irish", "supports_formality": False},
    {"language": "it", "name": "italian", "supports_formality": False},
    {"language": "ja", "name": "japanese", "supports_formality": False},
    {"language": "jw", "name": "javanese", "supports_formality": False},
    {"language": "kn", "name": "kannada", "supports_formality": False},
    {"language": "kk", "name": "kazakh", "supports_formality": False},
    {"language": "km", "name": "khmer", "supports_formality": False},
    {"language": "ko", "name": "korean", "supports_formality": False},
    {"language": "ku", "name": "kurdish", "supports_formality": False},
    # {"language": "ku", "name": "kurdish (kurmanji)", "supports_formality": False},
    {"language": "ky", "name": "kyrgyz", "supports_formality": False},
    {"language": "lo", "name": "lao", "supports_formality": False},
    {"language": "la", "name": "latin", "supports_formality": False},
    {"language": "lv", "name": "latvian", "supports_formality": False},
    {"language": "lt", "name": "lithuanian", "supports_formality": False},
    {"language": "lb", "name": "luxembourgish", "supports_formality": False},
    {"language": "mk", "name": "macedonian", "supports_formality": False},
    {"language": "mg", "name": "malagasy", "supports_formality": False},
    {"language": "ms", "name": "malay", "supports_formality": False},
    {"language": "ml", "name": "malayalam", "supports_formality": False},
    {"language": "mt", "name": "maltese", "supports_formality": False},
    {"language": "mi", "name": "maori", "supports_formality": False},
    {"language": "mr", "name": "marathi", "supports_formality": False},
    {"language": "mn", "name": "mongolian", "supports_formality": False},
    {"language": "my", "name": "myanmar", "supports_formality": False},
    # {"language": "my", "name": "myanmar (burmese)", "supports_formality": False},
    {"language": "ne", "name": "nepali", "supports_formality": False},
    {"language": "no", "name": "norwegian", "supports_formality": False},
    {"language": "or", "name": "odia", "supports_formality": False},
    {"language": "ps", "name": "pashto", "supports_formality": False},
    {"language": "fa", "name": "persian", "supports_formality": False},
    {"language": "pl", "name": "polish", "supports_formality": False},
    {"language": "pt", "name": "portuguese", "supports_formality": False},
    {"language": "pa", "name": "punjabi", "supports_formality": False},
    {"language": "ro", "name": "romanian", "supports_formality": False},
    {"language": "ru", "name": "russian", "supports_formality": False},
    {"language": "sm", "name": "samoan", "supports_formality": False},
    {"language": "gd", "name": "scots gaelic", "supports_formality": False},
    {"language": "sr", "name": "serbian", "supports_formality": False},
    {"language": "st", "name": "sesotho", "supports_formality": False},
    {"language": "sn", "name": "shona", "supports_formality": False},
    {"language": "sd", "name": "sindhi", "supports_formality": False},
    {"language": "si", "name": "sinhala", "supports_formality": False},
    {"language": "sk", "name": "slovak", "supports_formality": False},
    {"language": "sl", "name": "slovenian", "supports_formality": False},
    {"language": "so", "name": "somali", "supports_formality": False},
    {"language": "es", "name": "spanish", "supports_formality": False},
    {"language": "su", "name": "sundanese", "supports_formality": False},
    {"language": "sw", "name": "swahili", "supports_formality": False},
    {"language": "sv", "name": "swedish", "supports_formality": False},
    {"language": "tg", "name": "tajik", "supports_formality": False},
    {"language": "ta", "name": "tamil", "supports_formality": False},
    {"language": "te", "name": "telugu", "supports_formality": False},
    {"language": "th", "name": "thai", "supports_formality": False},
    {"language": "tr", "name": "turkish", "supports_formality": False},
    {"language": "uk", "name": "ukrainian", "supports_formality": False},
    {"language": "ur", "name": "urdu", "supports_formality": False},
    {"language": "ug", "name": "uyghur", "supports_formality": False},
    {"language": "uz", "name": "uzbek", "supports_formality": False},
    {"language": "vi", "name": "vietnamese", "supports_formality": False},
    {"language": "cy", "name": "welsh", "supports_formality": False},
    {"language": "xh", "name": "xhosa", "supports_formality": False},
    {"language": "yi", "name": "yiddish", "supports_formality": False},
    {"language": "yo", "name": "yoruba", "supports_formality": False},
    {"language": "zu", "name": "zulu", "supports_formality": False},
]
available_langs = deepl_langs + google_langs

# Regex patterns for content filtering (used in message listener)
URL_PATTERN = re.compile(r"https?://\S+", re.IGNORECASE)
CUSTOM_EMOJI_PATTERN = re.compile(r"<a?:\w+:\d+>")
DISCORD_MENTION_PATTERN = re.compile(r"<[@#][!&]?\d+>")
# Matches multiline ```code``` and inline `code`
CODE_BLOCK_PATTERN = re.compile(r"```[\s\S]*?```|`[^`]+`")
